version: "1.0"
account:
  login: 12345678
  password: "password"
  server: Rico-RTD
  balance-limit: 10 #1-100%
trade:
  mode: manual # manual, auto
  actions:
    fii:
      list:
        - MXRF11.SA
        - XPCM11.SA
        - STRX11.SA
      strategy:
        name: buy-hold # buy-hold, buy-sell
        toBuy:
          percentage: -15.0
        toSell:
          percentage: 15.0
    acao:
      list:
      - 'PETR4F.SA'
      strategy:
        name: buy-sell # buy-hold, buy-sell
        toBuy: 
          percentage: 10.0
        toSell:
          percentage: 10.0
    bdr:
      list:
        - NUBR33.SA
      strategy:
        name: buy-hold # buy-hold, buy-sell